name: 🔄 CI
on:
  workflow_dispatch:
env:
  CLOUDFLARE_ACCOUNT_ID: ${{secrets.cloudflare_account_id}}
  CLOUDFLARE_API_TOKEN: ${{secrets.cloudflare_api_token}}
  NODE_AUTH_TOKEN: ${{secrets.node_auth_token}}
  ZX_VERBOSE: true
permissions:
  actions: read
  contents: write
  id-token: write
  pull-requests: write
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
      - name: 📦 Installing dependencies
        run: pnpm install
      - name: 📦 Publish packages
        run: pnpm run publish
      - name: 🚀 Deploy documentation site
        run: pnpm run deploy
